### ISSUE TITLE
sal::object::Array needs metadata inspection interface

### ISSUE THREAD

**Issue by dezed** [simple-access-layer/source#17]
Given a pointer to an array attribute I need to determine its metadata. Shape etc. Not possible at the moment.

suggest
class IArray
{
virtual std::vector<uint64_t> shape()=0
virtual int el_type()=0
}

class ArrayBase : public IArray
{
int el_type(){ return m_el_type;}
etc....
}

template< T >
class Array : public ArrayBase
{
}

**Comment by qingfengxia** [comment]
C will see Array<T>  as Attritbute*,  Array have type_name() == "array",  then   array has "element_type_name()", which equals to numpy array dtype name. Although IArray yet defined, but info is ready as string.

**Comment by dezed** [comment]
There is no such class as Array only Array< T >. You cannot cast from Attribute* to Array*. If there is an attribute array and I have an Attribute pointer I cannot call element_type_name()

**Comment by qingfengxia** [comment]
I have 2 commit just sent in

simplify Atomic<T, attr> to Atomic<T> via `to_dtype<T>()`
unit test for C API buffer ponter Array<T>.data()

C++ template really make thing tricky.  let me think about any way to cast to Array<T> or make IArray



Qingfeng Xia
Senior Research Software Engineer, Culham Centre of Fusion Energy, UKAEA

https://github.com/qingfengxia
https://www.researchgate.net/profile/Qingfeng_Xia
personal website: https://www.iesensor.com

________________________________

**Comment by qingfengxia** [comment]
> There is no such class as Array only Array< T >. You cannot cast from Attribute* to Array*. If there is an attribute array and I have an Attribute pointer I cannot call element_type_name()

I am implementing Array interface now, you will see it next Monday

**Comment by qingfengxia** [comment]
IArray interface as base class for all Array<T> implemented and unit tested,   add a new C-API,  data_at() just like C++ at() but give void* address,  as operator can not be virtual function
`
        DT number1 = 20;
        DT* p = static_cast<DT*>(v.data_pointer());
        p[1] = number1;
        REQUIRE(*static_cast<DT*>(v.data_at(1)) == number1);
`

**Comment by dezed** [comment]
I suggest moving data_at() to the array_interface. That way you can avoid void* and return T*. Each subclass will need to implement this member function anyway and you can avoid losing the type safety when using void*. Once the type of IArray is known we can cast to Array<T>

T* Array::data_pointer();
T& Array::data_at()

**Comment by qingfengxia** [comment]
IArray class implemented
