### ISSUE TITLE
Array<bool> and Array<std::string> needs specialized and more unit tests

### ISSUE THREAD

**Issue by qingfengxia** [simple-access-layer/source#18]
Currently Array<bool> can not be costructed,  and it's buffer pointer can not be used, can not work as bool[] in C.          Array<std::string> buffer pointer is also not valid, not continuous in member.

**Comment by dezed** [comment]
Dont necessarily need contiguous data. Public  c++ interface allows element access only. I dont think there is a problem.

**Comment by qingfengxia** [comment]
done, see in-source doc for BoolArray and StringArray
