### ISSUE TITLE
Misunderstanding of the SAL data model and intended client implementation

### ISSUE THREAD

**Issue by CnlPepper** [simple-access-layer/source#22]
Looking at the current PRs, it appears there are some minor misunderstandings as to the object hierarchy and/or the object naming and the intent of the original c++ client code.

Can I ask that you please reread the data model, described here: https://simple-access-layer.github.io/documentation/datamodel.html

In summary:

* There is the data tree, it holds nodes.
* Nodes are either branches or objects.
* Leaf Nodes hold a DataObject
* A DataObject is instance of a DataClass.
* Every DataClass defines two representations: the DataObject and its DataSummary, the summary being a reduced version of the full object, where large attributes removed.
* DataClasses are built from Attributes.
* Every DataClass must have a core set of attributes, used by the SAL server to identify a type of data class for validation on the server, these are defined here: https://simple-access-layer.github.io/documentation/datamodel/datatree.html#common-structure
* Dataclasses are defined to represent Signals, Logs, Images etc....

When the client receives JSON that encodes a DataObject of DataSummary it should be decoded into a generic DataObject. In C++ this should be an actual, concrete class. In my C++ code this was called `Leaf` (as get() also has to return `Branch` and both are derived from sal::node::Object). This is what should be returned by the client in the first instance. This allows the client to handle any current and any FUTURE data class without needing to update the client code.

Any higher level object should simply subclass Leaf and expose the attributes as appropriate .i.e. a class hierarchy:

```
class Leaf {
  public: 
    string cls;
    string group;
    uint32_t version;
    ObjectType type; // full or summary
    Attribute::Branch root;
}

class Signal : protected Leaf {
  // validate and expose as appropriate
}

class SessionLog : protected Leaf {
  // validate and expose as appropriate
}

```

This means you can handle any unknown or unimplemented DataObject by default and you can add higher level wrappers for DataClasses at any point later. This decouples the server updates from the clients. A server can roll out a new supported dataclass and the client will still work, it just won't be converted into a nice tidy, specialised c++ object.

It was already in the code I handed over: https://github.com/simple-access-layer/source/blob/bc5b6da4bd4041f62f055f9da883ab1113c182eb/clients/c_cpp/include/sal.h#L967

The reason I raised this issue is also in part to try and dissuade you from continuing with the following development: https://github.com/simple-access-layer/source/blob/feature/sal_cpp/clients/c_cpp/include/sal_signal.h

The Leaf class already performs all the json decoding in a single code block, you should be using that layer, not rebuilding it at the lowest level again. Think about what happens if the core SAL API is updated... you'll end up having to update every single data object rather than just a single base class.

**Comment by CnlPepper** [comment]
I don't understand why the implementation of Leaf etc... was changed. That code was fully working, it just needed to be tidied up. I strongly suggest you revert the node namespace back to it's original form.

**Comment by qingfengxia** [comment]
It is hard to conceive some of your undocumeted thoughts, so I must understand the code from Python source code.  But given I can see your C++ is not exact same design as python, so my C++ does not needs to be exactly same.  

DataClass, kind of meta type system, it is easy to implemented in python decorator, it is just not worth of mimic it in C++. 

 E.g. I understand there are 2 inheritance trees one DataObject (in C++ Attribute) and *Summary in parallel in Python.  Summary encoding was not implemented then, and I think there is no need for another tree in C++, leading to large code duplication. And Summary Interface is sufficient.  The more code the more work for maintainance.

I do agree your most of points, except one,   the design of Leaf class:  Leaf derived from dataobject,   Leaf and branch are entries in FileSystem. Leaf class should holds only file meta data, permission , version, etc in C# FileInfo (returned by list(). just like  bash shell  `ls`,  or  Linux file system VFS API,   not the content of file that could be huge.   ( returned by get()).  I refactored a bit on node system, for the sake for easy understanding, the design must mimic some common stuff. like  `ls` command.  

Signal class is my first dataobject design, as I have no ideal what is other Log, Image data may looks like, so I have not done much abstraction. 
```
// instead of Leaf, I call it DataObject
class DataObject{      // this can also derive from Attribute, applying single root principle
  public: 
    string cls;
    string group;
    uint32_t version;
    ObjectType type; // full or summary
    Attribute::Branch root;        // why name as Branch?
}

Signal: public DataObject
```

**Comment by qingfengxia** [comment]
"Leaf Nodes hold a DataObject"  could  be implemented "Leaf Nodes hold a link to DataObject",  and will be useful if client will cache download data, but we decide not to do such complicated design.

**Comment by qingfengxia** [comment]
For "DataClass"  it hints like PyType,  static meta info,  "DataObject" is used in my vocabulary, but I will check python code, swtich back in Signal class. sal_signal.h.

**Comment by CnlPepper** [comment]
None if the items I'm describing are undocumented. They are documented in the data model and server REST API documentation. The layers of the system I have reiterated above.

I warned you during our discussion not to implement the C++ API like the python API. The C++ API is meant to be a thin wrapper on the REST API. There are only 4 types of item returned by an HTTP GET in the REST API (which handles both list() and get() depending on options).

list(): A branch report or leat report
get(): A branch object or a dataobject (currently mislabelled Leaf in the code).

As I said in the meeting, the Leaf object was meant to be relabelled to DataObject in sal::node.

The only thing you were meant to look at the pyhton API for was the client code, to inspire the implementation of list, get etc... but without the retries for authentication or the automatic decoding of the dataobject structure into a concrete python class like Signal.

**Comment by CnlPepper** [comment]
> I like your design in c++ to distiguish Attribute and DataObject (container of Attributes), which are different from Python.

This is not strictly true, this concept is in python too, but uses a python dictionary, not a class. The intermediate dictionary created when decoding the json is the equivalent of the DataObject (aka mislabelled Leaf in my C++ code). In this dictionary the attributes are implemented using numpy types and python containers. In C++ this entire layer had to be explicitly reimplemented with dedicated classes.

> DataClass, in python, involved some kind of meta type system, it is easy to implemented in python decorator, it is just not worth of mimicing it in C++.

This functionality should not be implemented in C++, it is purely there so that in python you can dynamically add additional dataclasses by installing packages (when coupled with a setup tools feature). 
 
> E.g. I understand there are 2 inheritance trees one DataObject (in C++ Attribute) and *Summary in parallel in Python. Summary encoding was not implemented then, and I think there is no need for another tree in C++, leading to large code duplication. And Summary Interface is sufficient. The more code the more work for maintainance.

You still seem to be missing that a data class has two representations. The summary is the same as the full, but large attributes e.g. arrays are removed. This is so the use can effectively request just the meta data of an object. Look at the JET dashboard datatree viewer, you can see the summary being used to populate the descriptions of the leaf objects (e.g. signal dimensions etc...).

In c++ code BOTH full and summary are represented by the same object ("Leaf"). If get(summary=True) is set the summary object version is retrieved. A flag on the Leaf object informs the user if the data returned is a full or summary version.

> I do agree your most of points, except one, the design of Leaf class: Leaf derived from dataobject, Leaf and branch are entries in FileSystem. Leaf class should holds only file meta data, permission , version, etc in C# FileInfo (returned by list(). just like bash shell `ls`, or Linux file system VFS API, not the content of file that could be huge. ( returned by get()). I refactored a bit on node system, for the sake for easy understanding, the design must mimic some common stuff. like `ls` command.

Hopefully my other comments should have answered this already.

**Comment by CnlPepper** [comment]
> "Leaf Nodes hold a DataObject" could be implemented "Leaf Nodes hold a link to DataObject", and will be useful if client will cache download data, but we decide not to do such complicated design.

Any caching in this system is done transparently at the HTTP layer, that was why it was built with a REST API.

**Comment by CnlPepper** [comment]
So in summary, I strongly recommend you go back to my version of sal::node. Relabel sal::node::Leaf to DataObject. As I said it was already functional, except for the need to tidy it up and switch to cleaner code techniques. Just implement Client.

Btw why did you rename sal::node::Object to NodeObject? It is under the namespace sal::node so it doesn't need another Node in the name: sal::node::NodeObject is redundant. The point of namespacing is to prevent redundant or verbose, globally unique naming.

**Comment by CnlPepper** [comment]
Just so you are aware, I intended to change the python API to return the raw dataobject dictionary when it can't find a suitable python class representation of a dataclass (again to handle a server adding a dataclass the client doesn't yet have a class for). Time simply got the better of that plan.

**Comment by qingfengxia** [comment]
> > E.g. I understand there are 2 inheritance trees one DataObject (in C++ Attribute) and *Summary in parallel in Python. Summary encoding was not implemented then, and I think there is no need for another tree in C++, leading to large code duplication. And Summary Interface is sufficient. The more code the more work for maintainance.

> You still seem to be missing that a data class has two representations. The summary is the same as the full, but large attributes e.g. arrays are removed. This is so the user can effectively request just the meta data of an object. Look at the JET dashboard datatree viewer, you can see the summary being used to populate the descriptions of the leaf objects (e.g. signal dimensions etc...).

Attribute class implements ISummary interface for encoding.  decoding summary representation for Dictionary class and Array has yet done, but will be just a if switch.

**Comment by CnlPepper** [comment]
> > > E.g. I understand there are 2 inheritance trees one DataObject (in C++ Attribute) and *Summary in parallel in Python. Summary encoding was not implemented then, and I think there is no need for another tree in C++, leading to large code duplication. And Summary Interface is sufficient. The more code the more work for maintainance.
> 
> > You still seem to be missing that a data class has two representations. The summary is the same as the full, but large attributes e.g. arrays are removed. This is so the user can effectively request just the meta data of an object. Look at the JET dashboard datatree viewer, you can see the summary being used to populate the descriptions of the leaf objects (e.g. signal dimensions etc...).
> 
> Attribute class implements ISummary interface for encoding. decoding summary representation for Dictionary class and Array has yet done, but will be just a if switch.

You shouldn't be implementing any of this functionality.

Let me walk you though the process step by step to explain what the c++ api is meant to do and how it should happen (and how I coded it):

Leaf (Data object) request via get(summary=False):

1. Request sent to server, asking for object=full: https://simple-access-layer.github.io/documentation/server/rest_api.html#id5
2. Server response: a json oject encoding the attributes of a full data object: https://simple-access-layer.github.io/documentation/server/rest_api.html#id7
3. Client creates a Leaf (to be renamed DataObject) instance with the class name, group name, version set to the data objects common attribute values defined in the datamodel. The type attribute is set to "full" as it is a full data object. The attributes are then decoded into the Leaf instance to recreate the attributes and structure defined in the JSON.
4. the Leaf is returned to the user.

Leaf (Data object) request via get(summary=True):

1. Request sent to server, asking for object=summary: https://simple-access-layer.github.io/documentation/server/rest_api.html#id5
2. Server response: a json oject encoding the attributes of a full data object: https://simple-access-layer.github.io/documentation/server/rest_api.html#id7
3. Client creates a Leaf (to be renamed DataObject) instance with the class name, group name, version set to the data objects common attribute values defined in the datamodel. The type attribute is set to "summary" as it is a full data object. The attributes are then decoded into the Leaf instance to recreate the attributes and structure defined in the JSON.
4. the Leaf is returned to the user.

**That is it.** it wasn't intended to decode the JSON into a Signal object or any other object. You are adding that all unnecessarily. Once you have the above implemented you have a minimal SAL API.

Once that works and ONLY when that works should you consider converting Leaf (again rename to DataObject)  objects to higher level concrete C++ implementations of the DataClasses as per Python. Though in all honesty you'll just be creating a rod for everyone's back if you do that. You'll have to have a system of class registration to cope with the dataclasses for JET source form a separate internal repository (they are not part of SAL core).

**Comment by CnlPepper** [comment]
Please see the comments on github, not email as I edited it for typos and github doesn't send an email on an edit.

**Comment by qingfengxia** [comment]
I agree to have a general "leaf data object " class to hold `get()` data,  leave user to parse the attribute tree.    Signal class is not part of core API, but part of demo.

**Comment by CnlPepper** [comment]
Regarding put(), users are expected to populate a full object version of a Leaf (aka DataObject) per the relevant dataclass specification. This object is parsed by put into json and sent.

The same object is used for put and get, it's meant to be symmetrical.

**Comment by qingfengxia** [comment]
sal_signal.h  will be moved to examples folder, and used only in demo.cpp,  it will not be a part of c++ API, but a show case, how user data can be decoded. this Signal modelled after online dataclass signal model and tested again data from server.

**Comment by CnlPepper** [comment]
Misunderstanding persists, issue being handled internally by UKAEA management.

**Comment by qingfengxia** [comment]
After almost all the code on my side, and reread your comment, I improved my understanding on SAL, thank you Alex. As I have not read the sever side code, so I did not know encode_summary is not necessary for client then, so I will split out "encode_summary()" from C++ into some internal branch.
