### ISSUE TITLE
What is the relationship between C++ Attribute and DataObject in documentation

### ISSUE THREAD

**Issue by qingfengxia** [simple-access-layer/source#28]
In python code, there is no Attribute class, while in Alex's C++ there exists.  For Attribute class there is no metadata encode and decoding,  but online doc. https://simple-access-layer.github.io/documentation/datamodel/dataclasses/scalar.html#full-object-definition

Full Object Definition
object: {
    _class: string = "scalar"
    _group: string = "core"
    _type: string = "object"
    _version: uint64 = 1
    description: string = $DOC_STRING
    value: $TYPE = $VALUE
}

I wonder what's Alex intention to implement for `DataObject <-> Attribute class mutual conversion`
For example, there is simple Scalar Attribute, but store as DataObject in data tree. Surely, there is no need for a new class. 

My plan: 
 make DataObject::encode_metadata() static, as well as DataObject::decode_metadata(), so it can convert any Attribute class to DataClass, and vice verse.  Demo will be ready the next day

https://simple-access-layer.github.io/documentation/datamodel/dataclasses/signal.html

**Comment by CnlPepper** [comment]
You are muddling up concepts/layers. There is *no* conversion.

A dataclass/object is a structure constructed from attributes e.g. uint32, float32, array<int8>.

The following is a dataclass definition, BUILT from attributes, it is NOT an attribute:
```
object: {
_class: string = "scalar"
_group: string = "core"
_type: string = "object"
_version: uint64 = 1
description: string = $DOC_STRING
value: $TYPE = $VALUE
}
```
_class is a string attribute of the data class 
_class is a string attribute of the data class
_class is a string attribute of the data class

**Comment by CnlPepper** [comment]
I described what you need to implement here: https://github.com/simple-access-layer/source/issues/22#issuecomment-625287000

You are not meant to be implementing the data classes. Everything listed here: https://simple-access-layer.github.io/documentation/datamodel/dataclasses.html is a *dataclass*.

**Comment by CnlPepper** [comment]
The C++ DataObject and Attribute classes implement the contents of the dictionary returned by the the decode method in python:

https://github.com/simple-access-layer/source/blob/a6e2d528f5b51639eb3bc5832c53894ff733ea10/sal/core/serialise.py#L254

This is why you can't find it, because in python it doesn't need to be a special set of classes or container - it's a dictionary of containing numpy or python objects representing the attributes.

In C++ this is the object the API returns. The C++ API stops are one layer lower than the Python API. To aid the users the C++ DataObject just picks out the common attributes and places them on the class itself.

**Comment by CnlPepper** [comment]
In my original code, everything you needed was already written and, baring potential bugs, working. The only effort needed to complete the API was: 

* implementation of decode_report() on line for 1089.
* implementation of authentication(), list(), get(), put(), copy() and delete() on lines 1149-1184.
* implementation of missing copy and move constructors.
* code tidy up and *maybe* modernisation.

**Comment by qingfengxia** [comment]
To summarize my change on your design 
1)  I split your Leaf class into Leaf(metadata) and DataObject(Leaf content) now in sal_data_object.h.  all your code are there.  reason explained in #22 .  I have not completed
2)  We captured the point from your last video call, Signal was not necessary, but later I thought signal class is needed in demo.cpp, if a useful demo is going to be implemented to match python demo. You may think it is still out of project scope, but it has been completed.   Iam moving sal_signal.h out of include/ today

Other than those 2, I have no plan to change any high level design, but tweak the code as requested by code review,  C-API design,  all public field encapsulation, simplify class template.

**Comment by qingfengxia** [comment]
We understand your concept that DataObject is in a higher layer than Attribute classes.  From coding perspective,  my understanding:    encoded Attribute + encoded metadata => encoded json DataObject.   For decoding json from server, just ignore metadata, it should give an Attribute like Scalar

**Comment by CnlPepper** [comment]
You'll need to explain what you mean by Attribute + encoded metadata, because as described this does not line up with the design.

An Attribute (e.g. a uint32 or array<int32>) is encoded into json and decoded from json. 

Int32 : Attribute -> encode as json-> { "type": "int32, "value": 24 }
{ "type": "int32, "value": 24 } -> decode from json -> Int32 : Attribute

see: https://simple-access-layer.github.io/documentation/server/rest_api.html#data-object-encoding
and the python implementation: https://github.com/simple-access-layer/source/blob/master/sal/core/serialise.py

There is *no* additional meta data, I don't understand where you are getting this idea from.

**Comment by CnlPepper** [comment]
I just went though sal_data_object.h. A data DataObject does not DERIVE from Attribute it CONTAINS Attributes.

You renaming of Branch to Dictionary is wrong, you have misunderstood the documentation.

The name Branch ioccurs in two seperate layers of the system:
1) a Branch node is the data tree layer (i.e. Virtual File System) that contains other nodes: https://simple-access-layer.github.io/documentation/datamodel/datatree.html#nodes
2) a Branch in a Dataclass structure is an attribute in a dataclass that contains other attributes: https://simple-access-layer.github.io/documentation/datamodel/datatree.html#data-classes

A Dictionary is a data class, it isn't a Branch: https://simple-access-layer.github.io/documentation/datamodel/dataclasses/dictionary.html

You keep muddling up names and concepts. These are clearly defined in the documentation as separate concepts in separate scopes/namespaces.

I don't have time to keep repeating myself. I'm doing this out of good will, but that is starting to run out. I've explained this to you *4* times. Once in the documentation, once in a video call and twice on here. The code I left you had all the relationships exactly as required by the data model. Those relationships don't need modified or changing. If you are deviating from that design, you are misunderstanding the system.

**Comment by qingfengxia** [comment]
The DataClass design was a bit outdated, when you last reply, now the DataObject is kind of stable. 

From lower lower Attribute to DataObject, I added one ctor to help
            /// constructor a DataObject from a single Attribute shared pointer
            ///
            /// the benefit of using constructor is that, all meta data will be set,
            /// single attribute data object: e.g. https://sal.jet.uk/data/pulse/latest?object=full

For  Object to Attribute,  just get_as<>()   , those are unit tested.

Regarding to "A DataObject does not DERIVE from Attribute it CONTAINS Attributes."
If DataObject, does not derive from Attribute, then how can DataObject derived class ptr can be added into std::map<std::string,  Attribute::Ptr> attributes.  Signal class has subobject, which you call it "branch". 


Regarding to "branch", I was very much confused read json from server, I guess there must be better English name other than Branch, although I am not a native English,  I just does not understhand why reuse the word "branch", 
[https://sal.jet.uk/data/pulse/83373/ppf/signal/jetppf/magn/ipla?object=full](url)
 **can a leaf type contains more branches?**

**Comment by qingfengxia** [comment]
search "Branch " in page https://simple-access-layer.github.io/documentation/datamodel/dataclasses/dictionary.html

2/23 ocurrance  in one line bears the meaning of  sub_data_object. 
"""
> Container

N dimensional array: array<TYPE>
Where array type is any one of the atomic types.

Branch: branch / {}
The branch type is equivalent to a Python dictionary with string keys.
"""
In python code, under dataclasses folder, there is "DictionarySummary" I did not find any class called Branch, so the easy way to fix, is to abondon the line `Branch: branch / {}`. 

Search Again, sal doc, as C++ is not complete, it is purely for python user, does not contain any "Attribute" keyword.  In the last video call, I raise the question, what is the relationship between python DataObject and C++ Attribute in the last 5 min, then we got "DataClass" is high-level and Attribute is low-level.  

 My question is #28 is techincally (how to code)  "I wonder what's Alex intention to implement for DataObject <-> Attribute class mutual conversion" , As there is some DataObject bears only single attribute, what is the best way to code, to let data flow upward and downward.  so and I list my plan to discuss, not to argue.

**Comment by qingfengxia** [comment]
Regarding: "You are muddling up concepts/layers. There is no conversion."

In C++, constructor  High(LowType lt)  make an implicit conversion.  conversion is such a big word, maybe not precise, I was confused, but not muddled.  Most misunderstanding comes from diff meaning of words in diff brains.

**Comment by CnlPepper** [comment]
> The DataClass design was a bit outdated, when you last replied, now (May 14) the DataObject is kind of stable.
> 
> From lower lower Attribute to DataObject, I added one ctor to help
> /// constructor a DataObject from a single Attribute shared pointer
> ///
> /// the benefit of using constructor is that, all meta data will be set,
> /// single attribute data object: e.g. https://sal.jet.uk/data/pulse/latest?object=full
> 
> For DataObject to Attribute, just get_as<>() , those are unit tested.
> 
> Regarding to "A DataObject does not DERIVE from Attribute it CONTAINS Attributes."
> If DataObject, does not derive from Attribute, then how can DataObject derived class ptr can be added into std::map<std::string, Attribute::Ptr> attributes. Signal class has subobject, which you call it "branch".

I asked you NOT to venture into this area of the system, you don't need any of it for the C++ API or to implement a demo.

Only the Signal object is recognised as a dataclass to the SAL server (note only Signal is in the object registry). In the python implementation of Signal, I reused the DataObject base class to implement sub object INTERNAL to Signal, as I designed the signal sub objects to follow the same pattern and as the data classes. 

I designed the system and wrote the documentation, when I tell you something is meant to behave a certain way it is not a bloody debate.

**Comment by CnlPepper** [comment]
> Regarding to "branch", I was very much confused read json from server, I guess there must be better English name other than Branch, although I am not a native English, I just does not understhand why reuse the word "branch",

Both the data tree and the data class internal structures are trees. Trees have branches and leaves. The data tree and data class are separate scopes.

> [https://sal.jet.uk/data/pulse/83373/ppf/signal/jetppf/magn/ipla?object=full](url)
> **can a leaf type contains more branches?**
> 
> search "Branch " in page https://simple-access-layer.github.io/documentation/datamodel/dataclasses/dictionary.html
> 
> 2/23 ocurrance in one line bears the meaning of sub_data_object.
> """
> 
> > Container
> 
> N dimensional array: array
> Where array type is any one of the atomic types.
> 
> Branch: branch / {}
> The branch type is equivalent to a Python dictionary with string keys.
> """
> In python code, under dataclasses folder, there is "DictionarySummary" I did not find any class called Branch, so the easy way to fix, is to abondon the line `Branch: branch / {}`.

A python dictionary is NOT a dataclass Dictionary. The Dictionary dataclass (and it's summary) are not Branches.

**Comment by qingfengxia** [comment]
I will switch to dev on internal gitlab, instead of publishing uncompleted code , which leads to misunderstanding. 

 BTW,   DataObject will not derive from Attributes, but a new filed std::map<string, DataObject::Ptr> will be added  to hold children DataObject.

**Comment by CnlPepper** [comment]
The misunderstanding is apparent from your comments on the issues, not just the code. This will end up in a code review at some point. If it isn't following the specification it will cause us a serious problem.

Stick to the scope you were instructed to stay within.

**Comment by CnlPepper** [comment]
FYI "Attribute" is a generic term to identify elements of a class or structure. It shoudln't need explaining: https://en.wikipedia.org/wiki/Class_(computer_programming)#Structure

**Comment by CnlPepper** [comment]
Query was fully answered in https://github.com/simple-access-layer/source/issues/28#issuecomment-626889062.

**Comment by dezed-ukaea** [comment]
Even though this issue has been closed I am going to comment.

I feel qingfengxia's confusion is understandable. I have read and reread the SAL documentation and this thread many times. It took a long time before understanding there are two "branches". A node branch and a dataclass  branch. They are different things. The advantage I have over many others is that my idiocy and failings have been demonstrated time and again. I also have an advantage in being a **native** English speaker. I expect to get things wrong but out of a meeting of several developers there was confusion over this issue in every developer.

**Comment by CnlPepper** [comment]
I answered the query multiple times in this and a previous issue. The c++ code I left, as stated, had all the relationships correctly defined, including two clearly separate branch objects in different namespaces. This was stated on no less than 4 occasions (also see issue #22) and repeatedly ignored. The work was not being performed with the documentation alone.

If there is a issue with specificity in the documentation I can address it or someone can raise a PR suggesting an improvement.

**Comment by CnlPepper** [comment]
For the avoidance of any doubt, here are the two separate objects in the code I left: 

sal::object::Branch: https://github.com/simple-access-layer/source/blob/bc5b6da4bd4041f62f055f9da883ab1113c182eb/clients/c_cpp/include/sal.h#L724

sal::node::Branch: https://github.com/simple-access-layer/source/blob/bc5b6da4bd4041f62f055f9da883ab1113c182eb/clients/c_cpp/include/sal.h#L935
